### ISSUE TITLE
The plugin is red in the plugin tab.

### ISSUE THREAD

**Issue by ZayroCxIzBack** [HellFirePvP/CustomMobs#27]
It does not work for me.

![image](https://cloud.githubusercontent.com/assets/24883427/21597731/c0862f08-d14f-11e6-9bc1-8a22139f55e8.png)

**Comment by ataranlen** [comment]
I'm guessing you're using Spigot 1.11.2? 

I would suggest including a log file to your ticket.

**Comment by HellFirePvP** [comment]
Yes (oups i might have missed to answer here)
Please have a look at what your console says on startup or include a log here.

**Comment by ZayroCxIzBack** [comment]
07:16:11] [Server thread/INFO]: [CustomMobs] Enabling CustomMobs v2.5
[07:16:11] [Server thread/INFO]: [CustomMobs] Invalid Minecraft Version!
[07:16:11] [Server thread/INFO]: [CustomMobs] CustomMobs 2.5 doesn't work with MC-Version 1.8! Disabling...
[07:16:11] [Server thread/INFO]: [CustomMobs] Disabling CustomMobs v2.5
[07:16:11] [Server thread/WARN]: java.lang.ClassCastException: net.minecraft.server.v1_8_R3.BiomeDecorator cannot be cast to java.util.List
[07:16:11] [Server thread/WARN]: 	at emp.HellFire.Cmobs.ConfigHandling.nms.Manipulator.clearNMSSpawnList(Manipulator.java:152)
[07:16:11] [Server thread/WARN]: 	at emp.HellFire.Cmobs.ConfigHandling.nms.Manipulator.clearNMSSpawnLists(Manipulator.java:143)
[07:16:11] [Server thread/WARN]: 	at emp.HellFire.Cmobs.ConfigHandling.nms.Manipulator.resetDefault(Manipulator.java:63)
[07:16:11] [Server thread/WARN]: 	at emp.HellFire.Cmobs.ConfigHandling.nms.MinecraftDefaultSettings.restoreDynamicWithAt(MinecraftDefaultSettings.java:20)
[07:16:11] [Server thread/WARN]: 	at emp.HellFire.Cmobs.ConfigHandling.nms.MinecraftDefaultSettings.restoreOcean(MinecraftDefaultSettings.java:14)
[07:16:11] [Server thread/WARN]: 	at emp.HellFire.Cmobs.ConfigHandling.nms.Manipulator.restoreDefaultMinecraft(Manipulator.java:20)
[07:16:11] [Server thread/WARN]: 	at emp.HellFire.Cmobs.CustomMobs.onDisable(CustomMobs.java:200)
[07:16:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323)
[07:16:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364)
[07:16:11] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
[07:16:11] [Server thread/WARN]: 	at emp.HellFire.Cmobs.CustomMobs.onEnable(CustomMobs.java:83)
[07:16:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[07:16:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[07:16:11] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[07:16:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[07:16:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[07:16:11] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[07:16:11] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[07:16:11] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[07:16:11] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[07:16:11] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524)
[07:16:11] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[07:16:11] [Server thread/INFO]: [CustomMobs] disabled!
[07:16:11] [Server thread/INFO]: [WorldEdit] Enabling Worl


Isnt it supposed to work with spigot 1.8.8?? (the latest version)

**Comment by ZayroCxIzBack** [comment]
Nevermind, that is the old log. From when i tried the 2.5 version.

**Comment by ZayroCxIzBack** [comment]
[07:25:04] [Server thread/INFO]: [CustomMobs] Loading CustomMobs v3.71
[07:25:04] [Server thread/INFO]: [CustomMobs] WorldGuard found! Region support enabled.
[07:25:04] [Server thread/INFO]: [CustomMobs] Patching failed.
[07:25:04] [Server thread/INFO]: [CustomMobs] The plugin will stop itself on startup to prevent further errors.

Is it world guard that is the problem????

**Comment by ataranlen** [comment]
You're running"v3.71" and are quite a few versions behind. You'll need to provide your entire log file for us to be able to debug. I would start by using the latest version of the plugin.

**Comment by HellFirePvP** [comment]
Yea you're outdated. not going to care about such an old version.

**Comment by ZayroCxIzBack** [comment]
Im running the 3.71 version.

[07:25:04] [Server thread/INFO]: [CustomMobs] Loading CustomMobs v3.71
[07:25:04] [Server thread/INFO]: [CustomMobs] WorldGuard found! Region support enabled.
[07:25:04] [Server thread/INFO]: [CustomMobs] Patching failed.
[07:25:04] [Server thread/INFO]: [CustomMobs] The plugin will stop itself on startup to prevent further errors.

Thats the only thing in the log that had anything with CustomMobs to do.

**Comment by ZayroCxIzBack** [comment]
The thing that im wondering, is it the plugin that dont support WorldGuard or is it because i have an old version of worldguard?

**Comment by ataranlen** [comment]
You have an old version of CustomMobs. It is impossible to support that version, as there have been so many updates to both CustomMobs and WorldGuard since then.

**Comment by ZayroCxIzBack** [comment]
But i have the 3.17 version..

![image](https://cloud.githubusercontent.com/assets/24883427/21651599/87ad5fde-d2a9-11e6-8634-0cd1ac4f8536.png)

**Comment by ZayroCxIzBack** [comment]
Please, this seems to be an awesome plugin. I really want to get this to work.

Server Version: Spigot 1.8.8
Plugin Version: 3.71

Everything should work, right?

**Comment by HellFirePvP** [comment]
You are using an outdated version, _please_ update, i'm not gonna look into any pre-4.0 issues anymore.

**Comment by ZayroCxIzBack** [comment]
But isnt the 3.71 the latest???

**Comment by ZayroCxIzBack** [comment]
Oh, wait. WTF it isnt updated at the bukkit page. :<<<<<

**Comment by ZayroCxIzBack** [comment]
Okay. So i updated to 4.17. Still the same problem though.

I will try updating my spigot to 1.10.2.

**Comment by ZayroCxIzBack** [comment]
Okay, i found a solution.

Just updated the server to 1.10.2, apparently the plugin doesnt work with 1.8.8.

**Comment by HellFirePvP** [comment]
http://i.imgur.com/0rxSy7H.png

Try reading plugin descriptions.
